name: Release TenoxUI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  releases: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create TenoxUI zip
        run: |
          cd packages/tenoxui
          zip -r ../../tenoxui.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: tenoxui.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}